= Lincride API
Hussayn Abdul-Samad O. <hussaynabdsamad07@gmail.com>
1.0, December 15, 2025
:toc:
:icons: font
:url-quickref: https://github.com/hussayn-dev/ride-hailing/

TIP: Always read the doc. Update it whenever necessary to allow others a smooth development experience.

== Clone Repository

Clone the repo:

[source,bash]
----
git clone https://github.com/hussayn-dev/ride-hailing/
cd ride-hailing
----

*Update the .env from the .env.sample* (you can copy it).

== Setup Local Development Environment

Setup your virtual environment using venv and poetry footnote:[Your local venv setup may be slightly different depending on your OS].

[source,bash]
----
py -m venv venv
source venv/bin/activate
pip install poetry
poetry install
----

Ensure that the latest version of Docker Desktop is installed: https://docs.docker.com/desktop/install/mac-install

== Quick Commands

[source,bash]
----
# Start local environment with Docker
docker compose up --build

# Start API manually with Daphne (if needed for WebSockets)
docker compose exec api daphne -b 0.0.0.0 -p 8008 core.asgi:application

# Start Kafka consumer to broadcast trip locations
docker compose exec api python manage.py consume_trip_locations

# Manage migrations
docker compose exec api python manage.py makemigrations
docker compose exec api python manage.py migrate

# Run tests
docker compose exec api python manage.py test
----

_Access the API documentation via Nginx at http://localhost:8009/api/v1/doc_

_Redis Commander UI: http://localhost:60081_

== Manage Migrations

Whenever you make changes to models, generate migrations locally before pushing your code:

[source,bash]
----
docker compose exec api python manage.py makemigrations
docker compose exec api python manage.py migrate
----

== Update Shared Repo

After deploying shared repo:

[source,bash]
----
poetry add <shared-repo-package>
docker compose build
----

.Table Contributors
|===
|Name |Role |Email
|Hussayn Abdul-Samad O. |SBE |hussaynabdsamad07@gmail.com
|===

[quote]
____
Happy Coding
____
