# Generated by Django 5.2.1 on 2025-12-14 19:59

import common.kgs
import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
import django.contrib.postgres.indexes
import django.db.models.deletion
import django.utils.timezone
import trip.enums
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientSubscribedTrip',
            fields=[
                ('id', models.CharField(db_index=True, default=common.kgs.generate_unique_id, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session_id', models.CharField(max_length=255)),
                ('subscribed_to', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), default=trip.enums.default_state, size=None)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TripSettingsConfig',
            fields=[
                ('id', models.CharField(db_index=True, default=common.kgs.generate_unique_id, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('radius', models.DecimalField(decimal_places=5, default=0.0, help_text='Route radius in meters', max_digits=20)),
                ('speed', models.DecimalField(decimal_places=5, default=0.0, help_text='Speed in km/h', max_digits=20)),
                ('speed_mps', models.DecimalField(decimal_places=5, default=0.0, help_text='Speed in meters per second', max_digits=20)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.CharField(db_index=True, default=common.kgs.generate_unique_id, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('starting_location', django.contrib.gis.db.models.fields.PointField(geography=True, help_text='Starting location (longitude, latitude)', srid=4326)),
                ('destination_location', django.contrib.gis.db.models.fields.PointField(geography=True, help_text='Destination location (longitude, latitude)', srid=4326)),
                ('current_location', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, help_text='Destination location (longitude, latitude)', null=True, srid=4326)),
                ('route_geometry', models.TextField(blank=True, help_text='Encoded polyline from Google Directions API', null=True)),
                ('route_geometry_decoded', django.contrib.gis.db.models.fields.LineStringField(geography=True, help_text='Route geometry as a LineString', srid=4326)),
                ('available_seats', models.PositiveSmallIntegerField(help_text='Number of seats available for riders')),
                ('is_ride_requests_allowed', models.BooleanField(default=False, help_text='Whether new riders can request to join this trip')),
                ('trip_status', models.CharField(choices=[('Completed', 'Completed'), ('Ongoing', 'Ongoing'), ('Failed', 'Failed'), ('Initiated', 'Initiated')], default='Initiated')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_last_updated', models.DateTimeField(auto_now=True)),
                ('distance', models.DecimalField(decimal_places=5, default=0.0, max_digits=20)),
                ('duration', models.CharField(blank=True, max_length=255, null=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created the trip, nullable for this assessment', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_trips', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TripLocationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', django.contrib.gis.db.models.fields.PointField(geography=True, help_text='location (longitude, latitude)', srid=4326)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_history', to='trip.trip')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='trip',
            index=django.contrib.postgres.indexes.GistIndex(fields=['starting_location'], name='trip_trip_startin_b2ca94_gist'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=django.contrib.postgres.indexes.GistIndex(fields=['destination_location'], name='trip_trip_destina_bfd198_gist'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=django.contrib.postgres.indexes.GistIndex(fields=['route_geometry_decoded'], name='trip_trip_route_g_024d22_gist'),
        ),
    ]
